// <auto-generated />
using System;
using CRUDAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRUDAPI.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20240822180213_criacaoBD")]
    partial class criacaoBD
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CRUDAPI.Models.Categoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CompeticaoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompeticaoId");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("CRUDAPI.Models.Competicao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BannerImagem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CompeticaoAberta")
                        .HasColumnType("bit");

                    b.Property<long?>("CompeticaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ConviteNecessarioId")
                        .HasColumnType("bigint");

                    b.Property<long>("CriadorUsuarioId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modalidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PagamentoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Pais")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompeticaoId");

                    b.HasIndex("ConviteNecessarioId");

                    b.HasIndex("CriadorUsuarioId");

                    b.HasIndex("PagamentoId");

                    b.ToTable("Competicoes");
                });

            modelBuilder.Entity("CRUDAPI.Models.Competidor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CriadorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CriadorId");

                    b.ToTable("Competidores");
                });

            modelBuilder.Entity("CRUDAPI.Models.Confronto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataTermino")
                        .HasColumnType("datetime2");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Confrontos");
                });

            modelBuilder.Entity("CRUDAPI.Models.ConfrontoInscricao", b =>
                {
                    b.Property<long>("ConfrontoId")
                        .HasColumnType("bigint");

                    b.Property<long>("InscricaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ConfrontoInscricaoPaiConfrontoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ConfrontoInscricaoPaiId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ConfrontoInscricaoPaiInscricaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.HasKey("ConfrontoId", "InscricaoId");

                    b.HasIndex("InscricaoId");

                    b.HasIndex("ConfrontoInscricaoPaiConfrontoId", "ConfrontoInscricaoPaiInscricaoId");

                    b.ToTable("ConfrontoInscricao");
                });

            modelBuilder.Entity("CRUDAPI.Models.ContaCorrente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Saldo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ContasCorrente");
                });

            modelBuilder.Entity("CRUDAPI.Models.Convite", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataResposta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Convites");
                });

            modelBuilder.Entity("CRUDAPI.Models.ConviteCompetidor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CompetidorId")
                        .HasColumnType("bigint");

                    b.Property<long>("ConviteId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CompetidorId");

                    b.HasIndex("ConviteId");

                    b.ToTable("ConvitesCompetidores");
                });

            modelBuilder.Entity("CRUDAPI.Models.Inscricao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoriaId")
                        .HasColumnType("bigint");

                    b.Property<long>("CompetidorId")
                        .HasColumnType("bigint");

                    b.Property<long>("PagamentoId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Posição")
                        .HasColumnType("int");

                    b.Property<long?>("PremioResgatavelId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.Property<bool>("WO")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CompetidorId");

                    b.HasIndex("PagamentoId");

                    b.HasIndex("PremioResgatavelId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Inscricoes");
                });

            modelBuilder.Entity("CRUDAPI.Models.Notificacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AnuncianteId")
                        .HasColumnType("bigint");

                    b.Property<string>("BannerImagem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataExpiracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PagamentoId")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoAnuncio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AnuncianteId");

                    b.HasIndex("PagamentoId");

                    b.ToTable("Notificacoes");
                });

            modelBuilder.Entity("CRUDAPI.Models.Pagamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AprovadorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DataRecebimento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataRequisicao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Moeda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TipoPagamento")
                        .HasColumnType("int");

                    b.Property<string>("TokenPagSeguro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("AprovadorId");

                    b.ToTable("Pagamentos");
                });

            modelBuilder.Entity("CRUDAPI.Models.PagamentoContaCorrente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ContaCorrenteId")
                        .HasColumnType("bigint");

                    b.Property<bool>("ContaCorrenteSolicitante")
                        .HasColumnType("bit");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PagamentoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ContaCorrenteId");

                    b.HasIndex("PagamentoId");

                    b.ToTable("PagamentoContasCorrente");
                });

            modelBuilder.Entity("CRUDAPI.Models.Premio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataEntrega")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PagamentoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PagamentoId");

                    b.ToTable("Premios");
                });

            modelBuilder.Entity("CRUDAPI.Models.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CpfCnpj")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("EmailConfirmado")
                        .HasColumnType("bit");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CpfCnpj")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SenhaHash")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CRUDAPI.Models.UsuarioNotificacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DataLeitura")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Lido")
                        .HasColumnType("bit");

                    b.Property<long>("NotificacaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("NotificacaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioNotificacoes");
                });

            modelBuilder.Entity("CRUDAPI.Models.Categoria", b =>
                {
                    b.HasOne("CRUDAPI.Models.Competicao", "Competicao")
                        .WithMany("Categorias")
                        .HasForeignKey("CompeticaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competicao");
                });

            modelBuilder.Entity("CRUDAPI.Models.Competicao", b =>
                {
                    b.HasOne("CRUDAPI.Models.Competicao", null)
                        .WithMany("EtapasAnteriores")
                        .HasForeignKey("CompeticaoId");

                    b.HasOne("CRUDAPI.Models.Convite", "ConviteNecessario")
                        .WithMany()
                        .HasForeignKey("ConviteNecessarioId");

                    b.HasOne("CRUDAPI.Models.Usuario", "CriadorUsuario")
                        .WithMany()
                        .HasForeignKey("CriadorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRUDAPI.Models.Pagamento", "Pagamento")
                        .WithMany()
                        .HasForeignKey("PagamentoId");

                    b.Navigation("ConviteNecessario");

                    b.Navigation("CriadorUsuario");

                    b.Navigation("Pagamento");
                });

            modelBuilder.Entity("CRUDAPI.Models.Competidor", b =>
                {
                    b.HasOne("CRUDAPI.Models.Usuario", "Criador")
                        .WithMany("Competidores")
                        .HasForeignKey("CriadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Criador");
                });

            modelBuilder.Entity("CRUDAPI.Models.ConfrontoInscricao", b =>
                {
                    b.HasOne("CRUDAPI.Models.Confronto", "Confronto")
                        .WithMany("ConfrontoInscricoes")
                        .HasForeignKey("ConfrontoId")
                        .IsRequired();

                    b.HasOne("CRUDAPI.Models.Inscricao", "Inscricao")
                        .WithMany("ConfrontoInscricoes")
                        .HasForeignKey("InscricaoId")
                        .IsRequired();

                    b.HasOne("CRUDAPI.Models.ConfrontoInscricao", "ConfrontoInscricaoPai")
                        .WithMany()
                        .HasForeignKey("ConfrontoInscricaoPaiConfrontoId", "ConfrontoInscricaoPaiInscricaoId");

                    b.Navigation("Confronto");

                    b.Navigation("ConfrontoInscricaoPai");

                    b.Navigation("Inscricao");
                });

            modelBuilder.Entity("CRUDAPI.Models.ContaCorrente", b =>
                {
                    b.HasOne("CRUDAPI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CRUDAPI.Models.ConviteCompetidor", b =>
                {
                    b.HasOne("CRUDAPI.Models.Competidor", "Competidor")
                        .WithMany("ConvitesCompetidor")
                        .HasForeignKey("CompetidorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRUDAPI.Models.Convite", "Convite")
                        .WithMany("ConvitesCompetidor")
                        .HasForeignKey("ConviteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competidor");

                    b.Navigation("Convite");
                });

            modelBuilder.Entity("CRUDAPI.Models.Inscricao", b =>
                {
                    b.HasOne("CRUDAPI.Models.Categoria", "Categoria")
                        .WithMany("Inscricoes")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRUDAPI.Models.Competidor", "Competidor")
                        .WithMany()
                        .HasForeignKey("CompetidorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRUDAPI.Models.Pagamento", "Pagamento")
                        .WithMany()
                        .HasForeignKey("PagamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRUDAPI.Models.Premio", "PremioResgatavel")
                        .WithMany()
                        .HasForeignKey("PremioResgatavelId");

                    b.HasOne("CRUDAPI.Models.Usuario", "Usuario")
                        .WithMany("Inscricoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Competidor");

                    b.Navigation("Pagamento");

                    b.Navigation("PremioResgatavel");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CRUDAPI.Models.Notificacao", b =>
                {
                    b.HasOne("CRUDAPI.Models.Usuario", "Anunciante")
                        .WithMany()
                        .HasForeignKey("AnuncianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRUDAPI.Models.Pagamento", "Pagamento")
                        .WithMany()
                        .HasForeignKey("PagamentoId");

                    b.Navigation("Anunciante");

                    b.Navigation("Pagamento");
                });

            modelBuilder.Entity("CRUDAPI.Models.Pagamento", b =>
                {
                    b.HasOne("CRUDAPI.Models.Usuario", "Aprovador")
                        .WithMany()
                        .HasForeignKey("AprovadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aprovador");
                });

            modelBuilder.Entity("CRUDAPI.Models.PagamentoContaCorrente", b =>
                {
                    b.HasOne("CRUDAPI.Models.ContaCorrente", "ContaCorrente")
                        .WithMany("PagamentoContasCorrente")
                        .HasForeignKey("ContaCorrenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRUDAPI.Models.Pagamento", "Pagamento")
                        .WithMany("PagamentoContasCorrente")
                        .HasForeignKey("PagamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContaCorrente");

                    b.Navigation("Pagamento");
                });

            modelBuilder.Entity("CRUDAPI.Models.Premio", b =>
                {
                    b.HasOne("CRUDAPI.Models.Pagamento", "Pagamento")
                        .WithMany()
                        .HasForeignKey("PagamentoId");

                    b.Navigation("Pagamento");
                });

            modelBuilder.Entity("CRUDAPI.Models.UsuarioNotificacao", b =>
                {
                    b.HasOne("CRUDAPI.Models.Notificacao", "Notificacao")
                        .WithMany("UsuariosAlvo")
                        .HasForeignKey("NotificacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRUDAPI.Models.Usuario", "Usuario")
                        .WithMany("AnunciosRecebidos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Notificacao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CRUDAPI.Models.Categoria", b =>
                {
                    b.Navigation("Inscricoes");
                });

            modelBuilder.Entity("CRUDAPI.Models.Competicao", b =>
                {
                    b.Navigation("Categorias");

                    b.Navigation("EtapasAnteriores");
                });

            modelBuilder.Entity("CRUDAPI.Models.Competidor", b =>
                {
                    b.Navigation("ConvitesCompetidor");
                });

            modelBuilder.Entity("CRUDAPI.Models.Confronto", b =>
                {
                    b.Navigation("ConfrontoInscricoes");
                });

            modelBuilder.Entity("CRUDAPI.Models.ContaCorrente", b =>
                {
                    b.Navigation("PagamentoContasCorrente");
                });

            modelBuilder.Entity("CRUDAPI.Models.Convite", b =>
                {
                    b.Navigation("ConvitesCompetidor");
                });

            modelBuilder.Entity("CRUDAPI.Models.Inscricao", b =>
                {
                    b.Navigation("ConfrontoInscricoes");
                });

            modelBuilder.Entity("CRUDAPI.Models.Notificacao", b =>
                {
                    b.Navigation("UsuariosAlvo");
                });

            modelBuilder.Entity("CRUDAPI.Models.Pagamento", b =>
                {
                    b.Navigation("PagamentoContasCorrente");
                });

            modelBuilder.Entity("CRUDAPI.Models.Usuario", b =>
                {
                    b.Navigation("AnunciosRecebidos");

                    b.Navigation("Competidores");

                    b.Navigation("Inscricoes");
                });
#pragma warning restore 612, 618
        }
    }
}
